# Generated by Django 4.1.3 on 2022-12-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('LastName', models.CharField(max_length=62)),
                ('FirstName', models.CharField(max_length=62)),
                ('BirthDate', models.DateField()),
                ('Address', models.CharField(max_length=24)),
                ('PhoneNumber', models.CharField(max_length=24)),
            ],
        ),
    ]
