# Generated by Django 4.1.3 on 2022-12-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThunderApp', '0002_users_activeuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='BirthDate',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='FirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='ActiveUser',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='LastName',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='PhoneNumber',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='UserId',
            new_name='userId',
        ),
    ]
