# Generated by Django 4.1.2 on 2022-12-19 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=62)),
                ('firstName', models.CharField(max_length=62)),
                ('birthDate', models.DateField()),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=24)),
                ('phone', models.CharField(max_length=24)),
                ('role', models.CharField(max_length=24)),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ThunderApp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Operadores',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ThunderApp.users')),
            ],
        ),
    ]
