# Generated by Django 4.1.2 on 2022-12-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThunderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
