# Generated by Django 4.1.2 on 2022-12-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThunderApp', '0003_alter_users_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='isActive',
            field=models.BooleanField(),
        ),
    ]
