# Generated by Django 4.1.3 on 2022-12-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThunderApp', '0003_rename_address_users_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='userId',
            new_name='id',
        ),
    ]
