# Generated by Django 4.1.3 on 2022-12-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThunderApp', '0005_alter_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(default='admin', max_length=24),
        ),
    ]
