# Generated by Django 4.1.3 on 2023-01-23 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ThunderApp', '0005_bills_remove_operadores_id_delete_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='idUser',
        ),
        migrations.AddField(
            model_name='users',
            name='idBill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ThunderApp.bills'),
        ),
    ]
