# Generated by Django 4.1.3 on 2023-01-23 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThunderApp', '0006_remove_bills_iduser_users_idbill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='payMethod',
        ),
    ]
