# Generated by Django 4.1.3 on 2023-01-23 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThunderApp', '0008_bills_paymethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='idBill',
        ),
    ]
