# Generated by Django 4.1.3 on 2023-01-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThunderApp', '0010_bills_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='userID',
            field=models.BigIntegerField(),
        ),
    ]
