# Generated by Django 4.1.3 on 2023-01-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThunderApp', '0012_bills_isgenerated'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='created',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastName',
            field=models.CharField(default='', max_length=62),
        ),
    ]
