# Generated by Django 4.1.3 on 2023-01-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThunderApp', '0014_remove_users_created_bills_createduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='createdUser',
        ),
    ]
