# Generated by Django 4.1.3 on 2023-02-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThunderApp', '0016_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
